/**
 * Excepcion de acceso a modulos
 *
 * @author tecso: 
 * @version  1.0
 */

package com.odhoman.api.utilities.access;

public class AccessException extends Exception {

	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 8452641379336789015L;

	private String error = "";

	public AccessException() {
		super();
	}

	public AccessException(String msg) {
		super(msg);
		this.setError(msg);
	}

	public AccessException(Exception e) {
		super(e);
	}

	public String getError() {
		return error;
	}

	public void setError(String error) {
		this.error = error;
	}

}
