/**
 * Helper
 *   RequestManagerException
 *
 * Extiende la clase Exception.
 *
 * @author tecso: 
 * @version  1.0
 */

package com.odhoman.api.utilities.web;

public class CmRequestManagerException extends Exception {

	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -6604759961399062332L;

	public CmRequestManagerException() {
		super();
	}

	public CmRequestManagerException(String msg) {
		super(msg);
	}

	public CmRequestManagerException(String message, Throwable cause) {
		super(message, cause);
	}

	public CmRequestManagerException(Throwable cause) {
		super(cause);
	}
	
}
