
/**
 * Common.java
 * Aloja la propiedades del objeto base del model
 *
 * @author tecso:
 * @version  1.0
 */

package com.odhoman.api.utilities;
                                                                         
import java.io.Serializable;
import java.util.Date;

public class Common implements Serializable {
    
	/**
	 * Autogenerated UID 
	 */
	private static final long serialVersionUID = -7783486873816313538L;

	public static final long LOCK_USER_UNIQUE = 0; /* opcion por defecto, 
    * intenta lockear siempre si existe otro registro
    * lokeado por el usuario lo libera (osea solo se permite un registro
    * loqueado por usuario
    */
    
    public static final long LOCK_NEVER = 1; /* no loquea nunca, 
    * la llamada a un metodo lock ignora la peticion de lockeo
    */

    public static final long ACCESS_SU_ID = -1; /* Id de super usuario */
    public static final String ACCESS_SU_NAME = "toor"; /* nombre super usuario */

    private String cmSessionId = "";
    private Long cmErrCode = new Long(0);
    private String cmErrDescription = "";
    private String cmAccessFlag = "";
    private Long cmLockFlag = new Long(Common.LOCK_USER_UNIQUE);  // por defecto lockuser
    private String cmActFunction = "";
    private String cmUserId = "";
    private Long cmUserKey = new Long(0);
    private String cmProfileId = "";
    private Long cmProfileKey = new Long(0);
    private Date cmRecTimestamp = new Date();
    private String cmApplicationId = "";

    public Common()  {
        super();
    }

    /** Copia este objeto a dest*/
    public void copy(Common dest) {
	dest.setCmSessionId(""); // para futuro uso de Login Bean
	dest.setCmUserId(this.getCmUserId());
	dest.setCmUserKey(this.getCmUserKey());
	dest.setCmProfileKey(this.getCmProfileKey());
	dest.setCmProfileId(this.getCmProfileId());
	dest.setCmApplicationId(this.getCmApplicationId());
	dest.setCmRecTimestamp(this.getCmRecTimestamp());
    }

    // errCode
    public Long getCmErrCode() { return this.cmErrCode;}
    public void setCmErrCode(Long cmErrCode) 
    { this.cmErrCode = cmErrCode;}
    
    // errDescription
    public String getCmErrDescription() { return this.cmErrDescription;}
    
    // si cmErrDescription="-", mantiene el valor actual de la propiedad
    public void setCmErrDescription(String cmErrDescription) 
    { 
        if(!cmErrDescription.equals("-"))
            this.cmErrDescription = cmErrDescription;
    }
    
    // accessFlag
    public String getCmAccessFlag() { return this.cmAccessFlag;}
    public void setCmAccessFlag(String cmAccessFlag) 
    { this.cmAccessFlag = cmAccessFlag;}

    // actFunction
    public String getCmActFunction() { return this.cmActFunction;}
    public void setCmActFunction(String cmActFunction) 
    { this.cmActFunction = cmActFunction;}
    
    // userId
    public String getCmUserId() { return this.cmUserId;}
    public void setCmUserId(String cmUserId) 
    { this.cmUserId = cmUserId;}
    
    // recTimeStamp
    public Date getCmRecTimestamp() { return this.cmRecTimestamp;}
    public void setCmRecTimestamp(Date cmRecTimestamp) 
    { this.cmRecTimestamp = cmRecTimestamp;}

    // userKey
    public Long getCmUserKey() { return this.cmUserKey;}
    public void setCmUserKey(Long cmUserKey)
    { this.cmUserKey = cmUserKey;}

    // profileId
    public String getCmProfileId() { return this.cmProfileId;}
    public void setCmProfileId(String cmProfileId)
    { this.cmProfileId = cmProfileId;}

    // profileKey
    public Long getCmProfileKey() { return this.cmProfileKey; }
    public void setCmProfileKey(Long cmProfileKey)
    { this.cmProfileKey = cmProfileKey;}

    // sessionId
    public String getCmSessionId() { return this.cmSessionId; }
    public void setCmSessionId(String cmSessionId)
    { this.cmSessionId = cmSessionId;}

    // applicationId
    public String getCmApplicationId() { return this.cmApplicationId;}
    public void setCmApplicationId(String cmApplicationId)
    { this.cmApplicationId = cmApplicationId;}

    // lockFlag
    public Long getCmLockFlag() { return this.cmLockFlag; }
    public void setCmLockFlag(Long cmLockFlag)
    { this.cmLockFlag = cmLockFlag;}
    
    public String toString() {
    	StringBuffer sb = new StringBuffer("Common: ");
    	sb.append(" cmSessionId=");
    	sb.append(cmSessionId);
    	sb.append(" cmErrCode=");
    	sb.append(cmErrCode);
    	sb.append(" cmErrDescription=");
    	sb.append(cmErrDescription);
    	sb.append(" cmAccessFlag=");
    	sb.append(cmAccessFlag);
    	sb.append(" cmLockFlag=");
    	sb.append(cmLockFlag);
    	sb.append(" cmActFunction=");
    	sb.append(cmActFunction);
    	sb.append(" cmUserId=");
    	sb.append(cmUserId);
    	sb.append(" cmUserKey=");
    	sb.append(cmUserKey);
    	sb.append(" cmProfileId=");
    	sb.append(cmProfileId);
    	sb.append(" cmProfileKey=");
    	sb.append(cmProfileKey);
    	sb.append(" cmRecTimestamp=");
    	sb.append(cmRecTimestamp);
    	sb.append(" cmApplicationId=");
    	sb.append(cmApplicationId);
    	return sb.toString();
    }

}
