/**
 * Excepcion de session de usuario
 *
 * @author tecso: 
 * @version  1.0
 */

package com.odhoman.api.utilities;

public class SessionException extends Exception {
	
	/**
	 * Autogenerated UID 
	 */
	private static final long serialVersionUID = -2571346631817563570L;

	public SessionException() {
		super();
	}

	public SessionException(String msg) {
		super(msg);
	}

	public SessionException(Exception e) {
		super(e);
	}
}
