/** 
 * Clase proxy a las propiedades de session de la applicacion.
 * Como el esquema de request/response de las applicaciones almacena
 * temporalmente los datos de en la session. Utilizamos esta clase para
 * colocar un solo item en el mapa de Atributos del Session. 
 * De esta manera agrupamos los objetos de retorno y mantenimiento de session
 * en una sola clase que facilita su administracion y evita la posible policion
 * de datos en la session del usuario.
 *
 * CHANGELOG
 * UseserSession se pasa al framework cracommon porque sera utilizada para identificar
 * y almacenar los datos del usuario, al llamar a servicios del framework (Menu, Logging, etc)
 * @author  tecso
 * @date    2004-03-04
 * @version 1.1
 */
package com.odhoman.api.utilities;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Set;

public class UserSession extends Common {

	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 8216019461916153412L;

	private HashMap<Object, Object> userMap = null;

	private String encPasswd = ""; // password encodeado

	private String userDes = ""; // descripcion usuario

	private String profileDes = ""; // descripcion del perfil

	private String cssStyle = "";// estilo de los menues
	
	public UserSession() {
		userMap = new HashMap<Object, Object>();
	}

	public void put(String name, Object obj) {
		userMap.put(name, obj);
	}

	@SuppressWarnings("unchecked")
	public <T> T get(String name) {
		return (T) userMap.get(name);
	}

	@SuppressWarnings("unchecked")
	public <T> T remove(String name) {
		return (T) userMap.remove(name);
	}

	public boolean contains(String key) {
		return userMap.get(key) != null;
	}
	
	public void clear() {
		userMap.clear();
	}

	@SuppressWarnings("unchecked")
	public <T> List<T> getKeys() {
		Set<T> keys = (Set<T>) userMap.keySet();
		
		List<T> keyList = new ArrayList<T>();		
		for(T key: keys) 
			keyList.add(key);
		return (List<T>) keyList; 
	}
	
	public String getEncPasswd() {
		return this.encPasswd;
	}

	public void setEncPasswd(String encPasswd) {
		this.encPasswd = encPasswd;
	}

	public String getUserDes() {
		return this.userDes;
	}

	public void setUserDes(String userDes) {
		this.userDes = userDes;
	}

	public String getCssStyle() {
		return this.cssStyle;
	}

	public void setCssStyle(String cssStyle) {
		this.cssStyle = cssStyle;
	}

	/**
	 * @return the profileDes
	 */
	public String getProfileDes() {
		return profileDes;
	}

	/**
	 * @param profileDes
	 *            the profileDes to set
	 */
	public void setProfileDes(String profileDes) {
		this.profileDes = profileDes;
	}

	public String toString() {
		StringBuffer sb = new StringBuffer("UserSession: ");
		sb.append(super.toString());
		sb.append(" - userDesc=");
		sb.append(userDes);
		sb.append(" profileDes=");
		sb.append(profileDes);
		sb.append(" encPasswd=");
		sb.append(encPasswd);
		sb.append(" cssStyle=");
		sb.append(cssStyle);
		sb.append(" userMap=");
		sb.append(userMap);
		return sb.toString();
	}
}
