package com.odhoman.api.utilities.transac;

public class ErrorCode extends MdTransaction {

	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 9216909902574927978L;
	
	public String errorCode = "";
	
	public ErrorCode() {
		super();
		setMdInfo();
	}
	
	public ErrorCode(String errorCode) {
		super();
		setMdInfo();
		setErrorCode(errorCode);
	}
	
	private void setMdInfo() {
		setFieldInfo("errorCode", "String", 3);
	}
	
	/**
	 * @return the errorCode
	 */
	public String getErrorCode() {
		return errorCode;
	}

	/**
	 * @param errorCode the errorCode to set
	 */
	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}
}
