/**
 * MdFieldProperty.java
 *
 * Almacena las propiedades de los campos de los objetos del modelo
 * 
 *
 * @author fg 
 * @version  1.0
 */

package com.odhoman.api.utilities.transac;

import java.io.Serializable;

public class MdFieldProperty implements Serializable {

	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 6637815149319620869L;

	// private
	private String fieldName = "";

	private String fieldDataType = "";

	private int fieldSize = 0;

	// if fieldDataType=double
	private int fieldNumDec = 0;

	// if fieldDataType=Collection
	private String itemDataType = "";

	private int itemSize = 0;

	private int itemNumDec = 0;

	private String relatedProperty = "";

	// public

	/* set */
	public void set_fieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public void set_fieldDataType(String fieldDataType) {
		this.fieldDataType = fieldDataType;
	}

	public void set_fieldSize(int fieldSize) {
		this.fieldSize = fieldSize;
	}

	public void set_fieldNumDec(int fieldNumDec) {
		this.fieldNumDec = fieldNumDec;
	}

	public void set_relatedProperty(String relatedProperty) {
		this.relatedProperty = relatedProperty;
	}

	public void set_itemDataType(String itemDataType) {
		this.itemDataType = itemDataType;
	}

	public void set_itemSize(int itemSize) {
		this.itemSize = itemSize;
	}

	public void set_itemNumDec(int itemNumDec) {
		this.itemNumDec = itemNumDec;
	}

	/* get */
	public String get_fieldName() {
		return this.fieldName;
	}

	public String get_fieldDataType() {
		return this.fieldDataType;
	}

	public int get_fieldSize() {
		return this.fieldSize;
	}

	public int get_fieldNumDec() {
		return this.fieldNumDec;
	}

	public String get_relatedProperty() {
		return this.relatedProperty;
	}

	public String get_itemDataType() {
		return this.itemDataType;
	}

	public int get_itemSize() {
		return this.itemSize;
	}

	public int get_itemNumDec() {
		return this.itemNumDec;
	}

}
