/**
 * MdTransaction.java
 * Aloja la propiedades de la clase que la implementa par el encodeo del mensaje
 *
 *
 * @author fg 
 * @version  1.0
 */

package com.odhoman.api.utilities.transac;

import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedList;

import com.odhoman.api.utilities.Common;

public class MdTransaction extends Common {

	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 2257004115608375817L;

	protected String transactionName;

	private Collection col = new LinkedList();

	/**
	 * Expone la coleccion de MdFieldProperty
	 * 
	 * @return Collection
	 */
	public Collection getFieldInfoCollection() {
		return col;
	}

	public String getDataType(String fieldName) {
		MdFieldProperty mdFieldProperty;
		String ret = "";

		for (Iterator it = col.iterator(); it.hasNext();) {
			mdFieldProperty = (MdFieldProperty) it.next();
			if (mdFieldProperty.get_fieldName().equals(fieldName)) {
				ret = mdFieldProperty.get_fieldDataType();
				break;
			}
		}
		return ret;
	}

	public int getSize(String fieldName) {
		MdFieldProperty mdFieldProperty;
		int ret = -1;

		for (Iterator it = col.iterator(); it.hasNext();) {
			mdFieldProperty = (MdFieldProperty) it.next();

			if (mdFieldProperty.get_fieldName().equals(fieldName)) {
				ret = mdFieldProperty.get_fieldSize();
				break;
			}
		}

		return ret;
	}

	/* setFieldInfo */

	// Simple fields
	public void setFieldInfo(String fieldName, String fieldDataType, int fieldSize) {
		MdFieldProperty mdFieldProperty = new MdFieldProperty();

		mdFieldProperty.set_fieldName(fieldName);
		mdFieldProperty.set_fieldDataType(fieldDataType);
		mdFieldProperty.set_fieldSize(fieldSize);

		col.add(mdFieldProperty);
	}

	// Simple fields with decimals
	public void setFieldInfo(String fieldName, String fieldDataType, int fieldSize, int fieldNumDec) {
		MdFieldProperty mdFieldProperty = new MdFieldProperty();

		mdFieldProperty.set_fieldName(fieldName);
		mdFieldProperty.set_fieldDataType(fieldDataType);
		mdFieldProperty.set_fieldSize(fieldSize);
		mdFieldProperty.set_fieldNumDec(fieldNumDec);

		col.add(mdFieldProperty);
	}

	// Coleccion

	/*******************************************************************************************************************
	 *  - Coleccion: Cantidad de elemento conocidos - Item: Tipo de datos simples sin decimales, largo conocido
	 * 
	 ******************************************************************************************************************/
	public void setFieldInfo(String fieldName, String fieldDataType, int fieldSize, String itemDataType, int itemSize) {
		MdFieldProperty mdFieldProperty = new MdFieldProperty();

		mdFieldProperty.set_fieldName(fieldName);
		mdFieldProperty.set_fieldDataType(fieldDataType);
		mdFieldProperty.set_fieldSize(fieldSize);

		mdFieldProperty.set_itemDataType(itemDataType);
		mdFieldProperty.set_itemSize(itemSize);

		col.add(mdFieldProperty);

	}

	/*******************************************************************************************************************
	 *  - Coleccion: Cantidad de elemento conocidos - Item: Tipo de datos con decimales, largo conocido
	 * 
	 ******************************************************************************************************************/
	public void setFieldInfo(String fieldName, String fieldDataType, int fieldSize, String itemDataType, int itemSize,
			int itemNumDec) {
		MdFieldProperty mdFieldProperty = new MdFieldProperty();

		mdFieldProperty.set_fieldName(fieldName);
		mdFieldProperty.set_fieldDataType(fieldDataType);
		mdFieldProperty.set_fieldSize(fieldSize);

		mdFieldProperty.set_itemDataType(itemDataType);
		mdFieldProperty.set_itemSize(itemSize);
		mdFieldProperty.set_itemNumDec(itemNumDec);

		col.add(mdFieldProperty);

	}

	/*******************************************************************************************************************
	 *  - Coleccion: Cantidad de elemento conocidos - Item: Objeto del modelo. (no se especifica el largo porque se
	 * obtiene del objeto)
	 * 
	 ******************************************************************************************************************/
	public void setFieldInfo(String fieldName, String fieldDataType, int fieldSize, String itemDataType) {
		MdFieldProperty mdFieldProperty = new MdFieldProperty();

		mdFieldProperty.set_fieldName(fieldName);
		mdFieldProperty.set_fieldDataType(fieldDataType);
		mdFieldProperty.set_fieldSize(fieldSize);

		mdFieldProperty.set_itemDataType(itemDataType);

		col.add(mdFieldProperty);

	}

	/*-------------*/

	/*******************************************************************************************************************
	 *  - Coleccion: Cantidad de elemento informada en una propiedad del objeto (relatedProperty) - Item: Tipo de datos
	 * sin decimales, largo conocido
	 * 
	 ******************************************************************************************************************/
	public void setFieldInfo(String fieldName, String fieldDataType, int fieldSize, String relatedProperty,
			String itemDataType, int itemSize) {
		MdFieldProperty mdFieldProperty = new MdFieldProperty();

		mdFieldProperty.set_fieldName(fieldName);
		mdFieldProperty.set_fieldDataType(fieldDataType);
		mdFieldProperty.set_fieldSize(fieldSize);
		mdFieldProperty.set_relatedProperty(relatedProperty);

		mdFieldProperty.set_itemDataType(itemDataType);
		mdFieldProperty.set_itemSize(itemSize);

		col.add(mdFieldProperty);
	}

	/*******************************************************************************************************************
	 *  - Coleccion: Cantidad de elemento informada en una propiedad del objeto (relatedProperty) - Item: Tipo de datos
	 * con decimales, largo conocido
	 * 
	 ******************************************************************************************************************/
	public void setFieldInfo(String fieldName, String fieldDataType, int fieldSize, String relatedProperty,
			String itemDataType, int itemSize, int itemNumDec) {
		MdFieldProperty mdFieldProperty = new MdFieldProperty();

		mdFieldProperty.set_fieldName(fieldName);
		mdFieldProperty.set_fieldDataType(fieldDataType);
		mdFieldProperty.set_fieldSize(fieldSize);
		mdFieldProperty.set_relatedProperty(relatedProperty);

		mdFieldProperty.set_itemDataType(itemDataType);
		mdFieldProperty.set_itemSize(itemSize);
		mdFieldProperty.set_itemNumDec(itemNumDec);

		col.add(mdFieldProperty);
	}

	/*******************************************************************************************************************
	 *  - Coleccion: Cantidad de elemento informada en una propiedad del objeto (relatedProperty) - Item: Objeto del
	 * modelo. (no se especifica el largo porque se obtiene del objeto)
	 * 
	 ******************************************************************************************************************/
	public void setFieldInfo(String fieldName, String fieldDataType, int fieldSize, String relatedProperty,
			String itemDataType) {
		MdFieldProperty mdFieldProperty = new MdFieldProperty();

		mdFieldProperty.set_fieldName(fieldName);
		mdFieldProperty.set_fieldDataType(fieldDataType);
		mdFieldProperty.set_fieldSize(fieldSize);
		mdFieldProperty.set_relatedProperty(relatedProperty);

		mdFieldProperty.set_itemDataType(itemDataType);

		col.add(mdFieldProperty);
	}

}
